# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tu.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1136, 599)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.file_button1 = QtWidgets.QPushButton(self.centralwidget)
        self.file_button1.setGeometry(QtCore.QRect(20, 100, 161, 31))
        self.file_button1.setObjectName("file_button1")
        self.file_button2 = QtWidgets.QPushButton(self.centralwidget)
        self.file_button2.setGeometry(QtCore.QRect(20, 270, 161, 31))
        self.file_button2.setObjectName("file_button2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(450, 70, 301, 371))
        self.frame.setMouseTracking(False)
        self.frame.setTabletTracking(False)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.process_btn1 = QtWidgets.QPushButton(self.frame)
        self.process_btn1.setGeometry(QtCore.QRect(50, 50, 201, 41))
        self.process_btn1.setObjectName("process_btn1")
        self.process_btn2 = QtWidgets.QPushButton(self.frame)
        self.process_btn2.setGeometry(QtCore.QRect(50, 120, 201, 41))
        self.process_btn2.setObjectName("process_btn2")
        self.process_btn3 = QtWidgets.QPushButton(self.frame)
        self.process_btn3.setGeometry(QtCore.QRect(50, 190, 201, 41))
        self.process_btn3.setObjectName("process_btn3")
        self.process_btn4 = QtWidgets.QPushButton(self.frame)
        self.process_btn4.setGeometry(QtCore.QRect(50, 260, 201, 41))
        self.process_btn4.setObjectName("process_btn4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(450, 50, 111, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(780, 50, 111, 20))
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(770, 70, 321, 371))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.smooth_btn1 = QtWidgets.QPushButton(self.frame_2)
        self.smooth_btn1.setGeometry(QtCore.QRect(60, 40, 201, 41))
        self.smooth_btn1.setObjectName("smooth_btn1")
        self.smooth_btn2 = QtWidgets.QPushButton(self.frame_2)
        self.smooth_btn2.setGeometry(QtCore.QRect(60, 110, 201, 41))
        self.smooth_btn2.setObjectName("smooth_btn2")
        self.smooth_btn3 = QtWidgets.QPushButton(self.frame_2)
        self.smooth_btn3.setGeometry(QtCore.QRect(60, 180, 201, 41))
        self.smooth_btn3.setObjectName("smooth_btn3")
        self.show_file1 = QtWidgets.QLabel(self.centralwidget)
        self.show_file1.setGeometry(QtCore.QRect(20, 140, 391, 21))
        self.show_file1.setText("No image loaded")
        self.show_file1.setObjectName("show_file1")
        self.show_file2 = QtWidgets.QLabel(self.centralwidget)
        self.show_file2.setGeometry(QtCore.QRect(20, 310, 391, 21))
        self.show_file2.setText("No image loaded")
        self.show_file2.setObjectName("show_file2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1136, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "2022 Opencvdl Hw1"))
        self.file_button1.setText(_translate("MainWindow", "Load Image 1"))
        self.file_button2.setText(_translate("MainWindow", "Load Image 2"))
        self.process_btn1.setText(_translate(
            "MainWindow", "1.1 Color Separation"))
        self.process_btn2.setText(_translate(
            "MainWindow", "1.2 Color Transformation"))
        self.process_btn3.setText(_translate(
            "MainWindow", "1.3 Color Detection"))
        self.process_btn4.setText(_translate("MainWindow", "1.4 Blending"))
        self.label.setText(_translate("MainWindow", "1. Image Processing"))
        self.label_2.setText(_translate("MainWindow", "2. Image Smoothing"))
        self.smooth_btn1.setText(_translate("MainWindow", "2.1 Guassian Blur"))
        self.smooth_btn2.setText(_translate(
            "MainWindow", "2.2 Bilateral filter"))
        self.smooth_btn3.setText(_translate("MainWindow", "2.3 Median filter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
