# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tu.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1062, 565)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.file_button1 = QtWidgets.QPushButton(self.centralwidget)
        self.file_button1.setGeometry(QtCore.QRect(40, 220, 161, 31))
        self.file_button1.setObjectName("file_button1")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(350, 90, 301, 371))
        self.frame.setMouseTracking(False)
        self.frame.setTabletTracking(False)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.edge_btn1 = QtWidgets.QPushButton(self.frame)
        self.edge_btn1.setGeometry(QtCore.QRect(50, 50, 201, 41))
        self.edge_btn1.setObjectName("edge_btn1")
        self.edge_btn2 = QtWidgets.QPushButton(self.frame)
        self.edge_btn2.setGeometry(QtCore.QRect(50, 120, 201, 41))
        self.edge_btn2.setObjectName("edge_btn2")
        self.edge_btn3 = QtWidgets.QPushButton(self.frame)
        self.edge_btn3.setGeometry(QtCore.QRect(50, 190, 201, 41))
        self.edge_btn3.setObjectName("edge_btn3")
        self.edge_btn4 = QtWidgets.QPushButton(self.frame)
        self.edge_btn4.setGeometry(QtCore.QRect(50, 260, 201, 41))
        self.edge_btn4.setObjectName("edge_btn4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 70, 111, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(680, 70, 111, 20))
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(670, 90, 321, 371))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.transform_btn1 = QtWidgets.QPushButton(self.frame_2)
        self.transform_btn1.setGeometry(QtCore.QRect(60, 50, 201, 41))
        self.transform_btn1.setObjectName("transform_btn1")
        self.transform_btn2 = QtWidgets.QPushButton(self.frame_2)
        self.transform_btn2.setGeometry(QtCore.QRect(60, 120, 201, 41))
        self.transform_btn2.setObjectName("transform_btn2")
        self.transform_btn3 = QtWidgets.QPushButton(self.frame_2)
        self.transform_btn3.setGeometry(QtCore.QRect(60, 190, 201, 41))
        self.transform_btn3.setObjectName("transform_btn3")
        self.transform_btn4 = QtWidgets.QPushButton(self.frame_2)
        self.transform_btn4.setGeometry(QtCore.QRect(60, 260, 201, 41))
        self.transform_btn4.setObjectName("transform_btn4")
        self.show_file1 = QtWidgets.QLabel(self.centralwidget)
        self.show_file1.setGeometry(QtCore.QRect(40, 260, 291, 21))
        self.show_file1.setText("")
        self.show_file1.setObjectName("show_file1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1062, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.file_button1.setText(_translate("MainWindow", "Load Image"))
        self.edge_btn1.setText(_translate("MainWindow", "3.1 Gaussian Blur"))
        self.edge_btn2.setText(_translate("MainWindow", "3.2 Sobel X"))
        self.edge_btn3.setText(_translate("MainWindow", "3.3 Sobel Y"))
        self.edge_btn4.setText(_translate("MainWindow", "3.4 Magnitude"))
        self.label.setText(_translate("MainWindow", "3. Edge Detection"))
        self.label_2.setText(_translate("MainWindow", "4. Transformation"))
        self.transform_btn1.setText(_translate("MainWindow", "4.1 Resize"))
        self.transform_btn2.setText(_translate("MainWindow", "4.2 Translation"))
        self.transform_btn3.setText(_translate("MainWindow", "4.3 Rotation, Scaling"))
        self.transform_btn4.setText(_translate("MainWindow", "4.4 Shearing"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
