# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(486, 485)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(90, 10, 301, 391))
        self.frame_3.setMouseTracking(False)
        self.frame_3.setTabletTracking(False)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.Load_Image_btn = QtWidgets.QPushButton(self.frame_3)
        self.Load_Image_btn.setGeometry(QtCore.QRect(50, 30, 201, 41))
        self.Load_Image_btn.setObjectName("Load_Image_btn")
        self.Ex5_btn1 = QtWidgets.QPushButton(self.frame_3)
        self.Ex5_btn1.setGeometry(QtCore.QRect(50, 110, 201, 41))
        self.Ex5_btn1.setObjectName("Ex5_btn1")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 111, 20))
        self.label_3.setObjectName("label_3")
        self.Ex5_btn2 = QtWidgets.QPushButton(self.frame_3)
        self.Ex5_btn2.setGeometry(QtCore.QRect(50, 160, 201, 41))
        self.Ex5_btn2.setObjectName("Ex5_btn2")
        self.Ex5_btn3 = QtWidgets.QPushButton(self.frame_3)
        self.Ex5_btn3.setGeometry(QtCore.QRect(50, 210, 201, 41))
        self.Ex5_btn3.setObjectName("Ex5_btn3")
        self.Ex5_btn4 = QtWidgets.QPushButton(self.frame_3)
        self.Ex5_btn4.setGeometry(QtCore.QRect(50, 260, 201, 41))
        self.Ex5_btn4.setObjectName("Ex5_btn4")
        self.Ex5_btn5 = QtWidgets.QPushButton(self.frame_3)
        self.Ex5_btn5.setGeometry(QtCore.QRect(50, 310, 201, 41))
        self.Ex5_btn5.setObjectName("Ex5_btn5")
        self.Image_text = QtWidgets.QLabel(self.frame_3)
        self.Image_text.setGeometry(QtCore.QRect(60, 80, 171, 16))
        self.Image_text.setObjectName("Image_text")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 486, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Load_Image_btn.setText(_translate("MainWindow", "Load Image"))
        self.Ex5_btn1.setText(_translate("MainWindow", "1. Show Images"))
        self.label_3.setText(_translate("MainWindow", "5.ResNet50"))
        self.Ex5_btn2.setText(_translate("MainWindow", "2. Show Distribution"))
        self.Ex5_btn3.setText(_translate("MainWindow", "3. Show Model Structure"))
        self.Ex5_btn4.setText(_translate("MainWindow", "4. Show Comparison"))
        self.Ex5_btn5.setText(_translate("MainWindow", "5. Inference"))
        self.Image_text.setText(_translate("MainWindow", "No Images"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
