# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(598, 565)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(140, 20, 391, 481))
        self.frame.setMouseTracking(False)
        self.frame.setTabletTracking(False)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.train_btn1 = QtWidgets.QPushButton(self.frame)
        self.train_btn1.setGeometry(QtCore.QRect(20, 120, 201, 41))
        self.train_btn1.setObjectName("train_btn1")
        self.train_btn2 = QtWidgets.QPushButton(self.frame)
        self.train_btn2.setGeometry(QtCore.QRect(20, 180, 201, 41))
        self.train_btn2.setObjectName("train_btn2")
        self.train_btn3 = QtWidgets.QPushButton(self.frame)
        self.train_btn3.setGeometry(QtCore.QRect(20, 240, 201, 41))
        self.train_btn3.setObjectName("train_btn3")
        self.train_btn4 = QtWidgets.QPushButton(self.frame)
        self.train_btn4.setGeometry(QtCore.QRect(20, 300, 201, 41))
        self.train_btn4.setObjectName("train_btn4")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 111, 20))
        self.label.setObjectName("label")
        self.train_btn5 = QtWidgets.QPushButton(self.frame)
        self.train_btn5.setGeometry(QtCore.QRect(20, 360, 201, 41))
        self.train_btn5.setObjectName("train_btn5")
        self.file_button1 = QtWidgets.QPushButton(self.frame)
        self.file_button1.setGeometry(QtCore.QRect(20, 40, 161, 31))
        self.file_button1.setObjectName("file_button1")
        self.show_file1 = QtWidgets.QLabel(self.frame)
        self.show_file1.setGeometry(QtCore.QRect(20, 80, 341, 21))
        self.show_file1.setText("")
        self.show_file1.setObjectName("show_file1")
        self.train_btn6 = QtWidgets.QPushButton(self.frame)
        self.train_btn6.setGeometry(QtCore.QRect(20, 420, 201, 41))
        self.train_btn6.setObjectName("train_btn6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 598, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.train_btn1.setText(_translate("MainWindow", "1. Show Train Images"))
        self.train_btn2.setText(_translate("MainWindow", "2. Show Model Structure"))
        self.train_btn3.setText(_translate("MainWindow", "3. Show Data Augmentation"))
        self.train_btn4.setText(_translate("MainWindow", "4. Show Accuracy and Loss"))
        self.label.setText(_translate("MainWindow", "5. Training"))
        self.train_btn5.setText(_translate("MainWindow", "5. Inference"))
        self.file_button1.setText(_translate("MainWindow", "Load Image"))
        self.train_btn6.setText(_translate("MainWindow", "Training New Model"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
